"""
Markdown report generation for Agent Readiness audit results.
Reports are saved to <repo>/reports/ (override with GFA_REPORTS_DIR).
"""

import os
from datetime import datetime, timezone
from pathlib import Path

REPORTS_DIR = os.environ.get(
    "GFA_REPORTS_DIR",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "reports"),
)

DIMENSIONS = [
    ("discoverability", "Discoverability", 0.15, "Can AI agents find this business?"),
    ("service_clarity", "Service Clarity", 0.15, "Can AI agents understand what services are offered?"),
    ("bookability", "Bookability", 0.20, "Can AI agents book an appointment directly?"),
    ("contactability", "Contactability", 0.15, "Can AI agents reach this business by phone or message?"),
    ("quotability", "Quotability", 0.10, "Can AI agents request a quote programmatically?"),
    ("verifiability", "Verifiability", 0.10, "Can AI agents verify legitimacy and quality?"),
    ("payability", "Payability", 0.15, "Can AI agents initiate or complete payment?"),
]


def _grade(score) -> str:
    """Convert a numeric score (0-100) to a letter grade."""
    if score is None:
        return "N/A"
    if score >= 90:
        return "A"
    if score >= 80:
        return "B"
    if score >= 70:
        return "C"
    if score >= 60:
        return "D"
    return "F"


def _grade_label(grade: str) -> str:
    labels = {
        "A": "Excellent",
        "B": "Good",
        "C": "Fair",
        "D": "Poor",
        "F": "Not Ready",
    }
    return labels.get(grade, "")


def _score_bar(score, width=20) -> str:
    """Simple text-based progress bar for markdown."""
    if score is None:
        return "N/A"
    filled = round(score / 100 * width)
    empty = width - filled
    return f"{'#' * filled}{'.' * empty}"


def _get_dim_data(score_result: dict, key: str) -> dict:
    """Extract dimension data from score_result. Returns dict with score, findings, recommendations."""
    dims = score_result.get("dimension_scores", score_result.get("dimensions", {}))
    # Try full key, then short key
    for k in [f"{key}_score", key]:
        if k in dims:
            val = dims[k]
            if isinstance(val, dict):
                return val
            return {"score": val, "findings": [], "recommendations": []}
    # Try top-level
    score_val = score_result.get(f"{key}_score")
    return {"score": score_val, "findings": [], "recommendations": []}


_STUB_BANNER = (
    "> **STUB OUTPUT — NOT A REAL ASSESSMENT.**\n"
    "> This report was generated by `score_engine_stub.py`, which fetches nothing and\n"
    "> measures nothing. Every number below is a hash-derived placeholder. The real\n"
    "> scoring engine is private. See the repository README.\n\n"
)


def generate_report(score_result: dict, benchmarks: dict = None) -> str:
    """
    Generate a full markdown report from a scoring result.

    score_result should contain:
        - business_name, url, domain
        - composite_score, grade
        - dimensions: dict keyed by dimension name, each with score, findings, recommendations
    benchmarks (optional): output of get_vertical_benchmarks()
    """
    _stub = (score_result.get("methodology_version") == "stub"
             or (score_result.get("_internal") or {}).get("stub") is True)
    business_name = score_result.get("business_name", "Unknown Business")
    url = score_result.get("url", "")
    domain = score_result.get("domain", "")
    composite = score_result.get("composite_score", 0)
    grade = score_result.get("grade", _grade(composite))
    now = datetime.now(timezone.utc).strftime("%B %d, %Y")

    lines = []

    # Header
    lines.append(f"# Agent Readiness Report")
    lines.append("")
    lines.append(f"**{business_name}**")
    lines.append(f"{url}")
    lines.append(f"Report generated: {now}")
    lines.append("")

    # Overall score
    lines.append("---")
    lines.append("")
    lines.append("## Overall Agent Readiness Score")
    lines.append("")
    lines.append(f"# {composite:.0f} / 100  ({grade})")
    lines.append("")
    lines.append(f"**{_grade_label(grade)}** -- {_readiness_summary(composite)}")
    lines.append("")

    # Dimension breakdown table
    lines.append("---")
    lines.append("")
    lines.append("## Score Breakdown")
    lines.append("")
    lines.append("| Dimension | Score | Grade | Weight | Bar |")
    lines.append("|-----------|------:|:-----:|-------:|-----|")

    for key, label, weight, _ in DIMENSIONS:
        dim = _get_dim_data(score_result, key)
        s = dim.get("score")
        g = _grade(s)
        score_str = f"{s:.0f}" if s is not None else "N/A"
        bar = _score_bar(s)
        lines.append(f"| {label} | {score_str} | {g} | {weight:.0%} | `{bar}` |")

    lines.append("")

    # Dimension details
    lines.append("---")
    lines.append("")
    lines.append("## Detailed Findings")
    lines.append("")

    all_recommendations = []

    for key, label, weight, description in DIMENSIONS:
        dim = _get_dim_data(score_result, key)
        s = dim.get("score")
        g = _grade(s)
        score_str = f"{s:.0f}/100" if s is not None else "N/A"

        lines.append(f"### {label}  ({score_str}, {g})")
        lines.append(f"*{description}*")
        lines.append("")

        findings = dim.get("findings", [])
        if findings:
            lines.append("**What's working:**")
            for f in findings:
                lines.append(f"- {f}")
            lines.append("")

        recommendations = dim.get("recommendations", [])
        if recommendations:
            lines.append("**Recommendations:**")
            for r in recommendations:
                rec_text = r if isinstance(r, str) else r.get("text", str(r))
                impact = r.get("impact", "medium") if isinstance(r, dict) else "medium"
                lines.append(f"- {rec_text}")
                all_recommendations.append({
                    "dimension": label,
                    "text": rec_text,
                    "impact": impact,
                    "score": s if s is not None else 50,
                })
            lines.append("")

        if not findings and not recommendations:
            lines.append("No detailed data available for this dimension.")
            lines.append("")

    # Benchmarks comparison
    if benchmarks and benchmarks.get("count", 0) > 0:
        lines.append("---")
        lines.append("")
        vertical = benchmarks.get("vertical", "your vertical")
        city = benchmarks.get("city")
        location_str = f" in {city}" if city else ""
        count = benchmarks.get("count", 0)
        lines.append(f"## How You Compare")
        lines.append(f"*vs. {count} other {vertical} businesses{location_str}*")
        lines.append("")
        lines.append("| Dimension | Your Score | Vertical Avg | Difference |")
        lines.append("|-----------|----------:|-------------:|-----------:|")

        bench_data = benchmarks.get("benchmarks", {})

        # Composite
        comp_bench = bench_data.get("composite_score", {})
        comp_avg = comp_bench.get("mean")
        if comp_avg is not None:
            diff = composite - comp_avg
            sign = "+" if diff >= 0 else ""
            lines.append(f"| **Overall** | **{composite:.0f}** | **{comp_avg:.0f}** | **{sign}{diff:.0f}** |")

        for key, label, _, _ in DIMENSIONS:
            dim = _get_dim_data(score_result, key)
            s = dim.get("score")
            col = f"{key}_score"
            b = bench_data.get(col, {})
            avg = b.get("mean")
            if s is not None and avg is not None:
                diff = s - avg
                sign = "+" if diff >= 0 else ""
                lines.append(f"| {label} | {s:.0f} | {avg:.0f} | {sign}{diff:.0f} |")
            else:
                s_str = f"{s:.0f}" if s is not None else "N/A"
                avg_str = f"{avg:.0f}" if avg is not None else "N/A"
                lines.append(f"| {label} | {s_str} | {avg_str} | -- |")

        lines.append("")

    # Priority action items
    if all_recommendations:
        lines.append("---")
        lines.append("")
        lines.append("## Priority Action Items")
        lines.append("")
        lines.append("The highest-impact steps to improve your Agent Readiness Score:")
        lines.append("")

        # Sort: high impact first, then by lowest dimension score
        impact_order = {"high": 0, "medium": 1, "low": 2}
        sorted_recs = sorted(
            all_recommendations,
            key=lambda r: (impact_order.get(r["impact"], 1), r["score"]),
        )

        for i, rec in enumerate(sorted_recs[:5], 1):
            impact_tag = rec["impact"].upper()
            lines.append(f"{i}. **[{impact_tag}]** {rec['text']}  ")
            lines.append(f"   *Dimension: {rec['dimension']}*")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*This report was generated by LeadSnare's Agent Readiness Audit.*")
    lines.append("*AI agents are beginning to book appointments, request quotes, and hire service")
    lines.append("providers on behalf of their users. This report measures how ready your business")
    lines.append("is to be discovered and transacted with by those agents.*")
    lines.append("")
    lines.append("**Next step:** Schedule a call to review these findings and discuss implementation.")
    lines.append("Book at: https://cal.com/marklaird/leadsnare-lead-systems-review")
    lines.append("")

    out = "\n".join(lines)
    return (_STUB_BANNER + out) if _stub else out


def _readiness_summary(score) -> str:
    """One-sentence summary based on composite score."""
    if score >= 90:
        return "This business is fully ready for AI agent interactions across all major dimensions."
    if score >= 80:
        return "This business is well-positioned for AI agents, with minor gaps to close."
    if score >= 70:
        return "This business has a reasonable foundation but significant gaps remain."
    if score >= 60:
        return "AI agents would struggle to do business here. Several critical capabilities are missing."
    if score >= 40:
        return "This business is largely unusable for AI agents. Major work needed."
    return "AI agents cannot do business here today. The infrastructure for agent interaction does not exist."


def save_report(report: str, domain: str) -> str:
    """
    Save a markdown report to <repo>/reports/[domain]-[date].md.
    Returns the file path.
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    # Clean domain for filename
    clean_domain = domain.replace("https://", "").replace("http://", "").replace("/", "_").strip("_")
    filename = f"{clean_domain}-{date_str}.md"
    filepath = os.path.join(REPORTS_DIR, filename)

    with open(filepath, "w") as f:
        f.write(report)

    return filepath


def generate_summary_line(score_result: dict) -> str:
    """
    One-line summary of a scoring result.
    Example: "example.com | Score: 34/100 (F) | Book: 0 | Contact: 65 | Pay: 0"
    """
    domain = score_result.get("domain", "unknown")
    composite = score_result.get("composite_score", 0)
    grade = score_result.get("grade", _grade(composite))

    parts = [f"{domain}", f"Score: {composite:.0f}/100 ({grade})"]

    short_labels = {
        "discoverability": "Disc",
        "service_clarity": "Svc",
        "bookability": "Book",
        "contactability": "Contact",
        "quotability": "Quote",
        "verifiability": "Verify",
        "payability": "Pay",
    }

    for key, short in short_labels.items():
        dim = _get_dim_data(score_result, key)
        s = dim.get("score")
        if s is not None:
            parts.append(f"{short}: {s:.0f}")
        else:
            parts.append(f"{short}: --")

    return " | ".join(parts)
